### PR TITLE
Update README.md with GPG examples

### PR DESCRIPTION
**Pull request by phocean**
Add contract examples with GPG support

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
The target repository leaves out `cd contracts` before `make install`.  Also it would be advisable to mention that the `contracts` source directory would have to be retained and returned to before running `make uninstall`

Otherwise looks OK.

I am not sure about adding unrelated contracts to the same package.  Probably best to create other repos.  Might also be worth mentioning in the README.md that individual contract files can just be downloaded and saved in ./local/share/contractor instead of installing the whole package.

**Comment by phocean** [comment]
Got it, I will sort it out asap.

**Comment by phocean** [comment]
I made the changes there:

https://github.com/phocean/contracts-gpg

I hope that it is fine now.

**Review by jeremypw — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
