### PR TITLE
transition org.elementary.* occurrences to io.elementary.*

### LINKED ISSUE #30: wrong RDNN for dbus service
The dbus service file is still named `org.elementary.contractor.service`, everything is being moved to `io.elementary.*` namespace.

### PR DESCRIPTION
**Pull request by JackKenney**
Fix #30 

transition org.elementary.* to io.elementary.*

This change includes org.elementary.contractor.service.in file:
_I have not tested this filechange to know if it will break anything else,_  but I did change all the occurrences in this repo that I found

### CODE REVIEW

**Comment by JackKenney** [comment]
Can someone point me in the right direction to make this work? 

Perhaps there is a problem with this making an elementary/docker:loki call?

**Comment by worldofpeace** [comment]
ping @codygarver @tintou @peteruithoven

**Comment by JackKenney** [comment]
It seems that by updating to the latest master, the issue I mentioned in my comment was solved and the automated check is now satisfied!

**Comment by jeremypw** [comment]
I think this will break several things, at least until the Granite library is updated to use the new Dbus service name.

**Pull request closed without merging**
